# Generated by Django 5.2.3 on 2025-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('revolution_time', models.FloatField()),
                ('rotation_time', models.FloatField()),
                ('radius', models.FloatField()),
                ('average_temp', models.FloatField()),
            ],
        ),
    ]
